### ISSUE TITLE
Rest api support 

### ISSUE THREAD

**Issue by JMcrafter26** [MCSManager/MCSManager#883]
Please add rest api support to the manager.
It would be very nice and useful to have an api to start/stop or even restart certain services.

Please think about it

Translated:
请在管理器中添加休息api支持。
如果能有一个api来启动/停止甚至重启某些服务，那将是非常好和有用的。

请考虑一下这个问题

**Comment by Bluemangoo** [comment]
https://docs.mcsmanager.com/#/zh-cn/instance/start_instance

https://docs.mcsmanager.com/#/zh-cn/instance/stop_instance

https://docs.mcsmanager.com/#/zh-cn/instance/kill_instance

https://docs.mcsmanager.com/#/zh-cn/instance/restart_instance

**Comment by unitwk** [comment]
MCSManager has had these apis all along, but because of the amount of work involved in translating the document, there was no time to write them to the English document.

You can try google Translate first to read the document, and I will gradually improve it later.

https://docs.mcsmanager.com/#/zh-cn/instance/create_instance
